spring:
  application:
    name: bwic-svc
server:
  port: 8087
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://localhost:8082/eureka